#-------------------------------------------------------
# PREVIEW环境配置区域
#-------------------------------------------------------
# 重要说明
# 此配置区域仅在PREVIEW环境中生效，只能定义测试环境中默认且长期
# 不变的配置项，例如预览环境中的通用超时时间等，外部资源如数据库
# 连接等请务必通过Apollo配置中心进行配置，切勿在此文件中定义
#-------------------------------------------------------
server:
  port: 38090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:sqlserver://10.7.11.96:1433;database=wind
      username: sa
      password: UJhHxnAwxdhTkQ4t
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initialSize: 15
      minIdle: 10
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 50
      filters: stat,wall,log4j2
  # redis配置
  redis:
    port: 6379
    #    host: cheftalk-redis-stg.54xvis.0001.cnn1.cache.amazonaws.com.cn
    # 目前官网无法联通aws redis,联通后需替换
    host: 127.0.0.1
    database: 4
    pool:
      max-idle: 8               ## 连接池中的最大空闲连接
      min-idle: 1               ## 连接池中的最小空闲连接
      max-active: 8             ## 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1              ## 连接池最大阻塞等待时间（使用负值表示没有限制）

  #email
  mail:
    host: smtp.cma-cgm.com
    port:
    username: wind-test@cma-cgm.com
    password:

wx:
  miniapp:
    configs:
      - appid: wxa026e360ceef2f02 #微信小程序的appid
        secret: 9d9b0473164f9aa44387ab22b287ee01 #微信小程序的Secret
        token: OhUkNyo963EETcR27uTQ2U9P2CVmVUrg #微信小程序消息服务器配置的token
        aesKey: 6Zsbjd1beGNR2WMg9u5dpO5tDdlkv3rYTEXtCDeEdH9 #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

logging:
  level:
    root: INFO
    org:
      springframework: INFO

com:
  iss:
    wind:
      client:
        id: beapp-wind
        url: https://auth-pre.cma-cgm.com/as/token.oauth2
        secret: 3cW2qfWgqx50GIepNAHWuyYTa5FSZbs1OLZzLK3wUxjUW0qQIpNKfpV7mBrRSt2l
      digital-api-url: https://digital-apis-uat.cma-cgm.com/
      digital-api-url-ecom: https://apis-uat.cma-cgm.com/uat-ecom/