#-------------------------------------------------------
# PROD环境配置区域
#-------------------------------------------------------
# 重要说明
# 此配置区域仅在PROD环境中生效，只能定义测试环境中默认且长期不变
# 的配置项，例如生产环境中的通用超时时间等，外部资源如数据库连接
# 等请务必通过Apollo配置中心进行配置，切勿在此文件中定义
#-------------------------------------------------------
server:
  port: 38000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:sqlserver://10.7.11.94:1433;database=wind
      username: sa
      password: 7xRsAaSNN0lCkI2Zzu7z
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initialSize: 15
      minIdle: 10
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 50
      filters: stat,wall,log4j2
  # redis配置
  redis:
    port: 6379
    #    host: cheftalk-redis-stg.54xvis.0001.cnn1.cache.amazonaws.com.cn
    # 目前官网无法联通aws redis,联通后需替换
    host: 127.0.0.1
    database: 4
    pool:
      max-idle: 8               ## 连接池中的最大空闲连接
      min-idle: 1               ## 连接池中的最小空闲连接
      max-active: 8             ## 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1              ## 连接池最大阻塞等待时间（使用负值表示没有限制）

  #email
  mail:
    host: smtp.cma-cgm.com
    port:
    username: shg.wind@cma-cgm.com
    password:

wx:
  miniapp:
    configs:
      - appid: wxbcfe1072de985b0d #微信小程序的appid
        secret: 6baf05128fc0cfa6844419d9e32aea1e #微信小程序的Secret
        token: OhUkNyo963EETcR27uTQ2U9P2CVmVUrg #微信小程序消息服务器配置的token
        aesKey: 6Zsbjd1beGNR2WMg9u5dpO5tDdlkv3rYTEXtCDeEdH9 #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

logging:
  level:
    root: INFO
    org:
      springframework: INFO

swagger:
  basic:
    enable: true
    username: admin
    password: yhJb2UpSvIumdbjCMHTuXRs4MYZmidyJ

com:
  iss:
    wind:
      client:
        id: beapp-wind
        url: https://auth.cma-cgm.com/as/token.oauth2
        secret: gpeKRDr4ar1HoPw41bAneLbTlAMYcTtXrfjb4sBSbiasUgIo3RJUInqEuLRZqLHT
      digital-api-url: https://digital-apis.cma-cgm.com/
      digital-api-url-ecom: https://apis.cma-cgm.com/prd-ecom/