#-------------------------------------------------------
# PROD环境配置区域
#-------------------------------------------------------
# 重要说明
# 此配置区域仅在PROD环境中生效，只能定义测试环境中默认且长期不变
# 的配置项，例如生产环境中的通用超时时间等，外部资源如数据库连接
# 等请务必通过Apollo配置中心进行配置，切勿在此文件中定义
#-------------------------------------------------------
server:
  port: 18000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:sqlserver://10.7.11.94:1433;database=wind
      username: sa
      password: 7xRsAaSNN0lCkI2Zzu7z
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initialSize: 15
      minIdle: 10
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 50
      filters: stat,wall,log4j2